environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    - APPVEYOR_BUILD_WORKER_IMAGE: macOS

platform: Any CPU
configuration: Release

before_build:
  - dotnet restore Ambermoon.net.sln --verbosity normal

build:
  parallel: true
  project: Ambermoon.net.sln

artifacts:
  - path: Ambermoon.net-Windows.zip
    name: Ambermoon.net-Windows
  - path: Ambermoon.net-Windows32Bit.zip
    name: Ambermoon.net-Windows32Bit
  - path: Ambermoon.net-Linux.tar.gz
    name: Ambermoon.net-Linux
  - path: Ambermoon.net-Mac.zip
    name: Ambermoon.net-Mac
  - path: Ambermoon.net-Windows-Standalone.zip
    name: Ambermoon.net-Windows-Standalone
  - path: Ambermoon.net-Windows32Bit-Standalone.zip
    name: Ambermoon.net-Windows32Bit-Standalone
  - path: Ambermoon.net-Linux-Standalone.tar.gz
    name: Ambermoon.net-Linux-Standalone
  - path: Ambermoon.net-Mac-Standalone.zip
    name: Ambermoon.net-Mac-Standalone
  - path: nuget\*.nupkg
    name: NugetPackages

after_build:
    - ps: if ($env:APPVEYOR_REPO_TAG -eq $true) { ./publish.ps1 }
    - ps: ./nuget.ps1

test: off

deploy:
  - provider: GitHub
    name: Ambermoon.net-Windows
    artifact: Ambermoon.net-Windows
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: 'Release $(APPVEYOR_REPO_TAG_NAME)'
    auth_token:
      secure: CP6qsCjIlyJrYsuHs4tzdrYUWOO83Jlx6/U0Gqtl/SicGmBaN1hrYUEk6RSL6D8j
    draft: true
    prerelease: true
    force_update: true
    on:
      APPVEYOR_REPO_TAG: true
  - provider: GitHub
    name: Ambermoon.net-Windows32Bit
    artifact: Ambermoon.net-Windows32Bit
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: 'Release $(APPVEYOR_REPO_TAG_NAME)'
    auth_token:
      secure: CP6qsCjIlyJrYsuHs4tzdrYUWOO83Jlx6/U0Gqtl/SicGmBaN1hrYUEk6RSL6D8j
    draft: true
    prerelease: true
    force_update: true
    on:
      APPVEYOR_REPO_TAG: true
  - provider: GitHub
    name: Ambermoon.net-Linux
    artifact: Ambermoon.net-Linux
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: 'Release $(APPVEYOR_REPO_TAG_NAME)'
    auth_token:
      secure: CP6qsCjIlyJrYsuHs4tzdrYUWOO83Jlx6/U0Gqtl/SicGmBaN1hrYUEk6RSL6D8j
    draft: true
    prerelease: true
    force_update: true
    on:
      APPVEYOR_REPO_TAG: true
  - provider: GitHub
    name: Ambermoon.net-Mac
    artifact: Ambermoon.net-Mac
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: 'Release $(APPVEYOR_REPO_TAG_NAME)'
    auth_token:
      secure: CP6qsCjIlyJrYsuHs4tzdrYUWOO83Jlx6/U0Gqtl/SicGmBaN1hrYUEk6RSL6D8j
    draft: true
    prerelease: true
    force_update: true
    on:
      APPVEYOR_REPO_TAG: true
  - provider: GitHub
    name: Ambermoon.net-Windows-Standalone
    artifact: Ambermoon.net-Windows-Standalone
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: 'Release $(APPVEYOR_REPO_TAG_NAME)'
    auth_token:
      secure: CP6qsCjIlyJrYsuHs4tzdrYUWOO83Jlx6/U0Gqtl/SicGmBaN1hrYUEk6RSL6D8j
    draft: true
    prerelease: true
    force_update: true
    on:
      APPVEYOR_REPO_TAG: true
  - provider: GitHub
    name: Ambermoon.net-Windows32Bit-Standalone
    artifact: Ambermoon.net-Windows32Bit-Standalone
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: 'Release $(APPVEYOR_REPO_TAG_NAME)'
    auth_token:
      secure: CP6qsCjIlyJrYsuHs4tzdrYUWOO83Jlx6/U0Gqtl/SicGmBaN1hrYUEk6RSL6D8j
    draft: true
    prerelease: true
    force_update: true
    on:
      APPVEYOR_REPO_TAG: true
  - provider: GitHub
    name: Ambermoon.net-Linux-Standalone
    artifact: Ambermoon.net-Linux-Standalone
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: 'Release $(APPVEYOR_REPO_TAG_NAME)'
    auth_token:
      secure: CP6qsCjIlyJrYsuHs4tzdrYUWOO83Jlx6/U0Gqtl/SicGmBaN1hrYUEk6RSL6D8j
    draft: true
    prerelease: true
    force_update: true
    on:
      APPVEYOR_REPO_TAG: true
  - provider: GitHub
    name: Ambermoon.net-Mac-Standalone
    artifact: Ambermoon.net-Mac-Standalone
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: 'Release $(APPVEYOR_REPO_TAG_NAME)'
    auth_token:
      secure: CP6qsCjIlyJrYsuHs4tzdrYUWOO83Jlx6/U0Gqtl/SicGmBaN1hrYUEk6RSL6D8j
    draft: true
    prerelease: true
    force_update: true
    on:
      APPVEYOR_REPO_TAG: true
  - provider: NuGet
    name: NugetPackages
    api_key:
      secure: UwVH6GHdh4zr7mDxC/HWXBQni/uzh36MV5lsXRmrgyyYEXJ67H63sI31QG4AByXY
    skip_symbols: true
