trigger:
- master
- refs/tags/v*

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'WindowsRelease'

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: echo Running Linux build
  - task: NuGetToolInstaller@1
  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(solution)'
  - script: |
      dotnet build -c Release '**/*.sln'
    condition: contains(variables['build.sourceBranch'], 'refs/heads/master')
  - powershell: publish.ps1
    env:
      isWindows: false
    condition: contains(variables['build.sourceBranch'], 'refs/tags/v*')
  - task: GitHubRelease@1
    displayName: 'Create Linux GitHub Release'      
    inputs:
      gitHubConnection: AmbermoonNetGitHub
      repositoryName: Pyrdacor/Ambermoon.net
      releaseTitle: 'Release $(tagName)'
      tagSource: gitTag
      tag: $(tagName)
      action: create
      assets: |
        $(Build.ArtifactStagingDirectory)/Ambermoon.net-Linux.tar.gz
      isDraft: true
      isPreRelease: true
    condition: contains(variables['build.sourceBranch'], 'refs/tags/v*')
- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - script: echo Running Win64 build
  - task: NuGetToolInstaller@1
  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(solution)'
  - task: VSBuild@1
    inputs:
      solution: '**/*.sln'
      platform: 'Any CPU'
      configuration: 'Release'
    condition: contains(variables['build.sourceBranch'], 'refs/heads/master')
  - powershell: publish.ps1
    env:
      isWindows: true
    condition: contains(variables['build.sourceBranch'], 'refs/tags/v*')
  - powershell: nuget.ps1
    env:
      isWindows: true
    condition: contains(variables['build.sourceBranch'], 'refs/tags/v*')
  - task: GitHubRelease@1
    displayName: 'Create Windows GitHub Release'      
    inputs:
      gitHubConnection: AmbermoonNetGitHub
      repositoryName: Pyrdacor/Ambermoon.net
      releaseTitle: 'Release $(tagName)'
      tagSource: gitTag
      tag: $(tagName)
      action: create
      assets: |
        $(Build.ArtifactStagingDirectory)/Ambermoon.net-Windows.zip
        $(Build.ArtifactStagingDirectory)/Ambermoon.net-Windows32Bit.zip
      isDraft: true
      isPreRelease: true
    condition: contains(variables['build.sourceBranch'], 'refs/tags/v*')
