trigger:
- master
- refs/tags/v*

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    solution: './Ambermoon.net.sln'
  steps:
  - script: echo Running Linux build
  - task: NuGetToolInstaller@1
  - script: |
      dotnet restore '$(solution)' --verbosity normal -r linux-x64
  - script: |
      dotnet build -c Release '$(solution)'
    condition: contains(variables['build.sourceBranch'], 'refs/heads/master')
  - task: PowerShell@2
    inputs:
      filePath: ./publish.ps1
    condition: contains(variables['build.sourceBranch'], 'refs/tags/v')
    displayName: Pack Linux stuff
  - task: GitHubRelease@1
    displayName: 'Create Linux GitHub Release'      
    inputs:
      gitHubConnection: github.com_Pyrdacor
      repositoryName: Pyrdacor/Ambermoon.net
      tagSource: gitTag
      tag: $(Build.SourceBranchName)
      title: 'Release $(Build.SourceBranchName)'
      action: create
      addChangeLog: false
      assets: |
        $(Build.ArtifactStagingDirectory)/Ambermoon.net-Linux.tar.gz
      isDraft: true
      isPreRelease: true
    condition: contains(variables['build.sourceBranch'], 'refs/tags/v')
- job: Windows
  pool:
    vmImage: 'windows-latest'
  variables:
    solution: '$(Build.SourcesDirectory)\Ambermoon.net.sln'
  steps:
  - script: echo Running Win64 build
  - task: NuGetToolInstaller@1
  - script: |
      cd '$(Build.SourcesDirectory'
      dotnet restore
  - task: VSBuild@1
    inputs:
      solution: '$(solution)'
      platform: 'Any CPU'
      configuration: 'Release'
    condition: contains(variables['build.sourceBranch'], 'refs/heads/master')
  - task: PowerShell@2
    inputs:
      filePath: ./publish.ps1
      arguments: >
        -winbuild
    condition: contains(variables['build.sourceBranch'], 'refs/tags/v')
    displayName: Pack Windows stuff
  - task: PowerShell@2
    inputs:
      filePath: ./nuget.ps1
      arguments: >
        -winbuild
    condition: contains(variables['build.sourceBranch'], 'refs/tags/v')
    displayName: Pack nuget packages
  - task: GitHubRelease@1
    displayName: 'Create Windows GitHub Release'      
    inputs:
      gitHubConnection: github.com_Pyrdacor
      repositoryName: Pyrdacor/Ambermoon.net
      tagSource: gitTag
      tag: $(Build.SourceBranchName)
      title: 'Release $(Build.SourceBranchName)'
      action: create
      addChangeLog: false
      assets: |
        $(Build.ArtifactStagingDirectory)/Ambermoon.net-Windows.zip
        $(Build.ArtifactStagingDirectory)/Ambermoon.net-Windows32Bit.zip
      isDraft: true
      isPreRelease: true
    condition: contains(variables['build.sourceBranch'], 'refs/tags/v')
